---
    - name: Add Nginx repository
      yum:
        name: epel-release
        state: latest
        
    - name: Install nginx
      yum:
        name: nginx
        state: latest
        
    - name: Starting nginx service
      service:
        name: nginx
        state: started
        enabled: yes
