---
    
    - name: Installing PostgreSQL repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
        state: present
    
    - name: Adding key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name:
      apt:
        update_cache: yes
    
    - name: Installing PostgreSQL
      apt:
        name: "{{ item }}"
      with_items: "{{ postgresql_packages }}"
    
    - name: Starting PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: Create sonar user
      sudo_user: postgres
      postgresql_user:
        name: "{{ sonarqube_user }}"
        password: "{{ sonarqube_pass }}"
        priv: '*.*:ALL'
        state: present
    
    - name: Create a new database with name sonar
      sudo_user: postgres
      postgresql_db:
        name: sonar
        owner: "{{ sonarqube_user }}"
        state: present
