---
    - name: Installing dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ dependencies }}"

    - name: Installing python dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pip_packages }}"

    - name: Installing PostgreSQL
      apt:
        name: "{{ item }}"
      with_items: "{{ postgresql_packages }}"
    
    - name: Starting PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: Create sonar user
      become_user: postgres
      postgresql_user:
        name: "{{ sonarqube_user }}"
        password: "{{ sonarqube_pass }}"
        state: present
    
    - name: Create a new database with name sonar
      become_user: postgres
      postgresql_db:
        name: sonar
        owner: "{{ sonarqube_user }}"
        state: present
