---

- hosts: sonarqubeTest
  become: yes
  become_user: root
  vars:
    download_path: "/opt"
    download_file: "mysql57-community-release-el7-11.noarch.rpm"
    download_url: "https://dev.mysql.com/get/{{ download_file }}"
    mysql_root_password: "@Mysqldbroot5"
    ansible_hostname: sonarqubeTest
    dependencies:
      - python-pip
      - MySQL-python
 
  tasks:
    - name: Installing dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ dependencies }}"

    - name: Installing pexpect module
      pip:
        name: pexpect
        version: 3.3

    - name: Add repository
      expect:
        command: 'yum install epel-release'
        responses:
          (?i)[y/d/N]: "y"

    - name: updating pip
      command: 'pip install --upgrade pip'

    - name: Adding mysql repository
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        validate_certs: no

    - name: Installing mysql repository
      yum: 
        name: /opt/{{ download_file }}
        state: present

    - name: Install mysql server
      yum:
        name: mysql-server
        state: present
    
    - name: Starting mysql service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Getting temporary password
      command: "sed -n -e 's/^.*localhost: //p' /var/log/mysqld.log"
      register: temporary_password

    - include: mysql_secure_installation.yml
