---

- hosts: sonarqubeTest
  become: yes
  become_user: root
  vars:
    download_path: "/opt"
    download_file: "mysql57-community-release-el7-11.noarch.rpm"
    download_url: "https://dev.mysql.com/get/{{ download_file }}"
    mysql_root_password: "@Mysqldbroot5"
    ansible_hostname: sonarqubeTest
    inventory_hostname: ansible
    sonarqube_user: sonarqube
    sonarqube_pass: "@Sonaruser123"
    dependencies:
      - python-pip
      - MySQL-python
 
  tasks:
    - name: Installing dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ dependencies }}"

    - name: Installing pexpect module
      pip:
        name: pexpect
        version: 3.3

    - name: Add repository
      expect:
        command: 'yum install epel-release'
        responses:
          (?i)[y/d/N]: "y"

    - name: updating pip
      command: 'pip install --upgrade pip'

    - name: Adding mysql repository
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        validate_certs: no

    - name: Installing mysql repository
      yum: 
        name: /opt/{{ download_file }}
        state: present

    - name: Install mysql server
      yum:
        name: mysql-server
        state: present
    
    - name: Starting mysql service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Getting temporary password
      command: "sed -n -e 's/^.*localhost: //p' /var/log/mysqld.log"
      register: temporary_password
      tags: secure_installation

    - name: Secure Installation
      expect:
        command: 'mysql_secure_installation'
        responses:
          'Enter password for user root:': "{{ temporary_password.stdout }}\n"
          'New password:': "{{ mysql_root_password }}\n"
          'Re-enter new password:': "{{ mysql_root_password }}\n"
          'Change the password for root ? \(Press y|Y for Yes, any other key for No\) :': "n\n"
          'Remove anonymous users? \(Press y|Y for Yes, any other key for No\) :': "y\n"
          'Disallow root login remotely? \(Press y|Y for Yes, any other key for No\) :': "y\n"
          'Remove test database and access to it? \(Press y|Y for Yes, any other key for No\) :': "y\n"
          'Reload privilege tables now? \(Press y|Y for Yes, any other key for No\) :': "y\n"
        echo: yes
      tags: secure_installation


    - name: Adding a sonarqube user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: "{{ sonarqube_user }}"
        password: "{{ sonarqube_pass }}"
        priv: '*.*:ALL'
        state: present 
