---

- hosts: sonarqubeTest
  become: yes
  become_user: root
  vars:
    download_path: "/opt"
    download_url: "https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm"
    mysql_root_password: "@Mysqldbroot5"
    ansible_hostname: sonarqubeTest
    inventory_hostname: ansible
    dependencies:
      - epel-release
      - python-pip
      - MySQL-python
 
  tasks:
    - name: Installing dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ dependencies }}"

    - name: updating pip
      command: 'pip install --upgrade pip'

    - name: Create the flask database
      mysql_db:
        name: flask_db
        state: present

    - name: Adding mysql repository
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        validate_certs: no

    - name: Installing mysql repository
      yum: 
        name: /opt/mysql57-community-release-el7-11.noarch.rpm
        state: present

    - name: Install mysql server
      yum:
        name: mysql-server
        state: present
    
    - name: Starting mysql service
      service:
        name: mysqld
        state: started
        enabled: yes

    - include: mysql_secure_installation.yml
