---

- hosts: sonarqubeTest
  become: yes
  become_user: root
  vars:
    download_path: "/opt"
    download_file: "mysql-community-release-el7-5.noarch.rpm"
    download_url: "http://repo.mysql.com/{{ download_file }}"
    mysql_root_password: "@Mysqldbroot5"
    ansible_hostname: sonarqubeTest
    inventory_hostname: ansible
    sonarqube_user: sonar
    sonarqube_pass: "sonar"
    dependencies:
      - python-pip
      - MySQL-python
 
  tasks:
    - name: Installing dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ dependencies }}"

    - name: Installing pexpect module
      pip:
        name: pexpect
        version: 3.3

    - name: Add repository
      expect:
        command: 'yum install epel-release'
        responses:
          (?i)[y/d/N]: "y"

    - name: updating pip
      command: 'pip install --upgrade pip'

    - name: Adding mysql repository
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        validate_certs: no

    - name: Installing mysql repository
      yum: 
        name: /opt/{{ download_file }}
        state: present

    - name: Updating system
      command: 'yum update -y' 

    - name: Install mysql server
      yum:
        name: mysql-server
        state: present
    
    - name: Starting mysql service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Secure Installation
      expect:
        command: 'mysql_secure_installation'
        responses:
          'Enter current password for root \(enter for none\):': "\n"
          'Set root password? [Y/n] ': "n\n"
          'Remove anonymous users? [Y/n] ': "Y\n"
          'Disallow root login remotely? [Y/n] ': "Y\n"
          'Remove test database and access to it? [Y/n] ': "Y\n"
          'Reload privilege tables now? [Y/n] ': "Y\n"
        echo: yes
      tags: secure_installation


    - name: Adding a sonarqube user
      mysql_user:
        login_user: root
        login_password: ""
        user: "{{ sonarqube_user }}"
        password: "{{ sonarqube_pass }}"
        priv: '*.*:ALL'
        state: present 

    - name: Create a new database with name 'sonar'
      mysql_db:
        login_user: root
        login_password: ""
        name: sonar
        state: present
