---

- hosts: localhost
  become: yes
  become_user: root
  
  tasks:
    - name: Add Nginx repository
      yum:
        name: epel-release
        state: latest
        
    - name: Install nginx
      yum:
        name: nginx
        state: latest
        
    - name: Starting nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Confirmation message
      command: echo "nginx installed Succedfully!"
