---

- hosts: sonarqubeTest
  become: yes
  become_user: root
  vars:
    package_name: jdk-8u131-linux-x64.tar.gz
    download_url: "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/{{ package_name }}"
    download_dir: /opt
    java_name: "{{ download_dir }}/jdk1.8.0_131"
    java_archive: "{{ download_dir }}/{{ package_name }}"

  tasks:
    - name: Download nginx
    - name: Install nginx
