---

- hosts: gitlab
  become: true
  vars:
    dependencies:
      - curl
      - policycoreutils-python
      - openssh-server 
      - cronie
  tasks:

    - name: Install Dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ dependencies }}"

    - name: Enable systemctl service
      service:
        name: sshd
        state: started
        enabled: true

    - name: Enable firewall service
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Enable firewall
      shell: 'firewall-cmd --permanent --add-service=http'

    - name: Reload Firewall
      service:
        name: firewalld
        state: reloaded
        enabled: true

    - name: Install Postfix
      yum :
        name: postfix
        state: latest

    - name: Start postfix service
      service:
        name: postfix
        state: started
        enabled: true

    - name: Adding git lab repo
      shell: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash'

    - name: Install gitlab package
      shell: 'sudo EXTERNAL_URL="http://gitlab.rajTest.com" yum -y install gitlab-ee'
